const KEY='hisab-khata-v1';
const BACKUP_KEY='hisab-khata-auto-backup-v1';
const defaultState={products:[],sales:[],expenses:[],purchases:[],assets:[],settings:{capital:0}};
let raw=JSON.parse(localStorage.getItem(KEY)||'null');
if(raw){try{localStorage.setItem(BACKUP_KEY,JSON.stringify(raw));}catch(e){}}
let state={...defaultState,...(raw||{})};
state.products=Array.isArray(state.products)?state.products:[];
state.sales=Array.isArray(state.sales)?state.sales:[];
state.expenses=Array.isArray(state.expenses)?state.expenses:[];
state.purchases=Array.isArray(state.purchases)?state.purchases:[];
state.assets=Array.isArray(state.assets)?state.assets:[];
state.settings={...defaultState.settings,...(state.settings||{})};
// Backward-compatible migration: old expenses remain untouched; only missing fields are added.
state.expenses=state.expenses.map(e=>({...e,category:e.category||'অন্যান্য',type:e.type||'operating'}));
let page='dashboard';
const bn=n=>new Intl.NumberFormat('bn-BD',{maximumFractionDigits:2}).format(Number(n)||0);
const money=n=>'৳ '+bn(n);
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const sum=(arr,fn)=>arr.reduce((x,v)=>x+(Number(fn(v))||0),0);
function salesTotal(a=state.sales){return sum(a,s=>s.qty*s.price)}
function cogsTotal(a=state.sales){return sum(a,s=>s.qty*s.cost)}
function profitTotal(a=state.sales){return salesTotal(a)-cogsTotal(a)}
function expenseTotal(a=state.expenses){return sum(a,e=>e.type==='asset'?0:e.amount)}
function cashOutflowExpenses(a=state.expenses){return sum(a,e=>e.amount)}
function purchaseTotal(a=state.purchases){return sum(a,p=>p.qty*p.price)}
function assetTotal(a=state.assets){return sum(a,a=>a.amount)}
function stockQty(){return sum(state.products,p=>p.stock)}
function stockValue(){return sum(state.products,p=>p.stock*p.cost)}
function totalSold(){return sum(state.sales,s=>s.qty)}
function accountBalance(account){
 const capital=Number(state.settings.capital)||0;
 const sales=sum(state.sales,s=>s.payment===account?s.qty*s.price:0);
 const exp=sum(state.expenses,e=>e.payment===account?e.amount:0);
 const pur=sum(state.purchases,p=>p.payment===account?p.qty*p.price:0);
 const assets=sum(state.assets,a=>a.payment===account?a.amount:0);
 return (account==='Cash'?capital:0)+sales-exp-pur-assets;
}
function totalCash(){return ['Cash','bKash','Nagad','Bank'].reduce((x,a)=>x+accountBalance(a),0)}
function render(){document.getElementById('app').innerHTML=`<div class="app"><div class="layout"><aside class="sidebar"><div class="brand">📒 হিসাব খাতা</div>${nav('dashboard','🏠','Dashboard')}${nav('sales','💰','Sales')}${nav('products','📦','Products / Stock')}${nav('purchases','🛒','Purchases')}${nav('expenses','💸','Expenses')}${nav('money','💳','Money')}${nav('reports','📊','Reports')}<div style="margin-top:25px">${nav('settings','⚙️','Settings')}</div></aside><main class="main"><div class="topbar"><div><h1>${title()}</h1><div class="label">সহজে হিসাব রাখুন, দ্রুত সিদ্ধান্ত নিন</div></div><button class="iconbtn" onclick="downloadBackup()">⬇️</button></div>${content()}</main></div><button class="fab" onclick="openSale()">＋ Sale</button><nav class="bottom">${navb('dashboard','🏠','Home')}${navb('sales','💰','Sales')}${navb('products','📦','Stock')}${navb('more','⋯','More')}</nav></div>`}
function nav(p,i,t){return `<button class="navbtn ${page===p?'active':''}" onclick="go('${p}')">${i} &nbsp; ${t}</button>`}
function navb(p,i,t){return `<button class="${page===p?'active':''}" onclick="go('${p}')">${i}<br>${t}</button>`}
function title(){return ({dashboard:'Dashboard',sales:'Sales',products:'Products / Stock',purchases:'Purchases',expenses:'Expenses',money:'Money',reports:'Reports',settings:'Settings',more:'More'})[page]||'হিসাব খাতা'}
function content(){if(page==='dashboard')return dashboard();if(page==='sales')return sales();if(page==='products')return products();if(page==='purchases')return purchases();if(page==='expenses')return expenses();if(page==='money')return moneyPage();if(page==='reports')return reports();if(page==='settings'||page==='more')return settings();return dashboard()}
function dashboard(){const ts=state.sales.filter(s=>s.date===today());const te=state.expenses.filter(e=>e.date===today());const gross=profitTotal();const op=expenseTotal();return `<div class="card hero"><div class="label">আজকের বিক্রি</div><div class="money">${money(salesTotal(ts))}</div><div>${bn(sum(ts,s=>s.qty))} pcs sold</div></div><div class="grid stats"><div class="card stat"><div class="label">মোট বিক্রি</div><div class="value">${money(salesTotal())}</div></div><div class="card stat"><div class="label">গ্রস লাভ</div><div class="value profit">${money(gross)}</div></div><div class="card stat"><div class="label">ব্যবসায়িক খরচ</div><div class="value">${money(op)}</div></div><div class="card stat"><div class="label">নিট লাভ</div><div class="value ${gross-op<0?'negative':'profit'}">${money(gross-op)}</div></div></div><div class="grid stats"><div class="card stat"><div class="label">মোট স্টক</div><div class="value">${bn(stockQty())} pcs</div></div><div class="card stat"><div class="label">স্টকের ক্রয়মূল্য</div><div class="value">${money(stockValue())}</div></div><div class="card stat"><div class="label">মাল কেনা</div><div class="value">${money(purchaseTotal())}</div></div><div class="card stat"><div class="label">হাতে ব্যবসার টাকা</div><div class="value">${money(totalCash())}</div></div></div><div class="section"><div class="sectionhead"><h2>আজকের খরচ</h2><button class="btn secondary" onclick="go('expenses')">খরচ যোগ করুন</button></div><div class="card"><div class="money">${money(cashOutflowExpenses(te))}</div><div class="label">আজকের ব্যবসায়িক খরচ</div></div></div><div class="section"><div class="sectionhead"><h2>Business Position</h2></div><div class="card"><div class="label">Cash + Stock Value</div><div class="money">${money(totalCash()+stockValue())}</div><div class="label">Cash ${money(totalCash())} • Stock ${money(stockValue())}</div></div></div><div class="section"><div class="sectionhead"><h2>সাম্প্রতিক বিক্রি</h2><button class="btn secondary" onclick="go('sales')">সব দেখুন →</button></div>${salesList(state.sales.slice().reverse().slice(0,5))}</div>`}
function sales(){const ts=state.sales.filter(s=>s.date===today());return `<div class="card hero"><div class="label">Today's Sales</div><div class="money">${money(salesTotal(ts))}</div><div>${bn(sum(ts,s=>s.qty))} pcs sold</div></div><div class="section"><div class="sectionhead"><h2>➕ Add Sale</h2></div><div class="card form"><div class="field"><label>Product</label><select id="saleProduct" onchange="saleTotalPreview()">${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${bn(p.stock)} pcs</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="saleQty" type="number" min="1" value="1" oninput="saleTotalPreview()"></div><div class="field"><label>Selling Price / pcs</label><input id="salePrice" type="number" min="0" step="0.01" value="0" oninput="saleTotalPreview()"></div><div class="totalrow"><span>Total Sale</span><span id="salePreview">৳ 0</span></div><div class="field"><label>Payment</label>${paymentSelect('salePayment')}</div><button class="btn primary" onclick="addSale()" ${state.products.length?'':'disabled'}>✓ SAVE SALE</button>${state.products.length?'':'<div class="label">আগে Products / Stock থেকে অন্তত একটি পণ্য যোগ করুন।</div>'}</div></div><div class="section"><div class="sectionhead"><h2>TODAY'S SALES</h2></div>${salesList(ts.slice().reverse())}</div>`}
function paymentSelect(id,value='Cash'){return `<select id="${id}">${['Cash','bKash','Nagad','Bank'].map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select>`}
function salesList(arr){if(!arr.length)return '<div class="card empty">আজ এখনো কোনো বিক্রি নেই।</div>';return `<div class="list">${arr.map(s=>`<div class="item"><div><h3>🛍️ ${esc(s.productName)}</h3><p>${bn(s.qty)} pcs × ${money(s.price)} · ${esc(s.payment)} · ${s.date}</p></div><div style="text-align:right"><strong>${money(s.qty*s.price)}</strong><div class="actions"><button class="mini" onclick="editSale('${s.id}')">✏️</button><button class="mini danger" onclick="deleteSale('${s.id}')">🗑️</button></div></div></div>`).join('')}</div>`}
function products(){return `<div class="card hero"><div class="label">Current Stock Value</div><div class="money">${money(stockValue())}</div><div>${bn(stockQty())} pcs</div></div><div class="sectionhead"><h2>সব পণ্য</h2><button class="btn primary" onclick="openProduct()">＋ Add Product</button></div>${!state.products.length?'<div class="card empty">কোনো পণ্য নেই।</div>':`<div class="list">${state.products.map(p=>`<div class="item"><div><h3>📦 ${esc(p.name)}</h3><p>Purchase Price: ${money(p.cost)} / pcs</p><p>Stock: <span class="${p.stock<=5?'low':''}">${bn(p.stock)} pcs</span></p><p>Stock Value: <strong>${money(p.stock*p.cost)}</strong></p></div><div class="actions"><button class="mini" onclick="viewProduct('${p.id}')">Details</button><button class="mini" onclick="editProduct('${p.id}')">✏️</button><button class="mini danger" onclick="deleteProduct('${p.id}')">🗑️</button></div></div>`).join('')}</div>`}`}
function purchases(){return `<div class="card hero"><div class="label">মোট মাল কেনা</div><div class="money">${money(purchaseTotal())}</div><div>${state.purchases.length}টি purchase record</div></div><div class="section"><div class="sectionhead"><h2>➕ মাল কেনা / Stock In</h2></div><div class="card form"><div class="field"><label>Product</label><select id="purProduct">${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} — বর্তমান ${bn(p.stock)} pcs</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="purQty" type="number" min="1" value="1" oninput="purchasePreview()"></div><div class="field"><label>Purchase Price / pcs</label><input id="purPrice" type="number" min="0" step="0.01" value="0" oninput="purchasePreview()"></div><div class="totalrow"><span>Total Purchase</span><span id="purPreview">৳ 0</span></div><div class="field"><label>Payment</label>${paymentSelect('purPayment')}</div><button class="btn primary" onclick="addPurchase()" ${state.products.length?'':'disabled'}>✓ SAVE PURCHASE</button>${state.products.length?'':'<div class="label">আগে একটি Product তৈরি করুন।</div>'}</div></div><div class="section"><h2>Purchase History</h2><div class="list">${state.purchases.slice().reverse().map(p=>`<div class="item"><div><h3>🛒 ${esc(p.productName)}</h3><p>${bn(p.qty)} pcs × ${money(p.price)} · ${esc(p.payment)} · ${p.date}</p></div><div><strong>${money(p.qty*p.price)}</strong></div></div>`).join('')||'<div class="card empty">কোনো purchase record নেই।</div>'}</div></div>`}
function expenses(){const op=expenseTotal(),all=cashOutflowExpenses();return `<div class="grid stats"><div class="card stat"><div class="label">ব্যবসায়িক খরচ</div><div class="value">${money(op)}</div></div><div class="card stat"><div class="label">সব Cash Outflow</div><div class="value">${money(all)}</div></div></div><div class="section"><div class="sectionhead"><h2>➕ Add Expense</h2></div><div class="card form"><div class="field"><label>Expense Title</label><input id="expTitle" placeholder="যাতায়াত / দোকান ভাড়া / Packaging"></div><div class="field"><label>Category</label><select id="expCategory">${['যাতায়াত','দোকান ভাড়া','সরঞ্জাম','Packaging','Marketing','খাবার','Delivery','Utility','Communication','অন্যান্য'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Type</label><select id="expType"><option value="operating">Business Expense</option><option value="asset">Asset / Equipment Purchase</option></select></div><div class="field"><label>Amount</label><input id="expAmount" type="number" min="0" placeholder="500"></div><div class="field"><label>Payment</label>${paymentSelect('expPayment')}</div><button class="btn primary" onclick="addExpense()">✓ SAVE EXPENSE</button><div class="label">ব্যক্তিগত খরচ Business Expense হিসেবে দেবেন না। Table/Equipment চাইলে Asset হিসেবে দিন।</div></div></div><div class="section"><h2>Expense History</h2><div class="list">${state.expenses.slice().reverse().map(e=>`<div class="item"><div><h3>💸 ${esc(e.title)}</h3><p>${esc(e.category||'অন্যান্য')} · ${e.type==='asset'?'Asset':'Business Expense'} · ${e.date} · ${esc(e.payment)}</p></div><div><strong>${money(e.amount)}</strong><button class="mini danger" onclick="deleteExpense('${e.id}')">🗑️</button></div></div>`).join('')||'<div class="card empty">কোনো খরচ নেই।</div>'}</div></div>`}
function moneyPage(){return `<div class="card hero"><div class="label">মোট ব্যবসার হাতে টাকা</div><div class="money">${money(totalCash())}</div><div>Capital ${money(state.settings.capital||0)} • Stock Value ${money(stockValue())}</div></div><div class="section"><div class="sectionhead"><h2>Payment Accounts</h2></div><div class="grid stats">${['Cash','bKash','Nagad','Bank'].map(a=>`<div class="card stat"><div class="label">${a}</div><div class="value">${money(accountBalance(a))}</div></div>`).join('')}</div></div><div class="section"><div class="card"><h2>ব্যবসার মূলধন</h2><p class="label">শুধু শুরুতে ব্যবসায় ঢোকানো নিজের/বিনিয়োগের টাকা লিখুন।</p><div class="form"><div class="field"><label>Opening Capital</label><input id="capitalInput" type="number" min="0" value="${Number(state.settings.capital)||0}"></div><button class="btn primary" onclick="saveCapital()">✓ SAVE CAPITAL</button></div></div></div>`}
function reports(){const exp=expenseTotal(),salesv=salesTotal(),cogs=cogsTotal(),gross=salesv-cogs,net=gross-exp;return `<div class="grid stats"><div class="card stat"><div class="label">Total Sales</div><div class="value">${money(salesv)}</div></div><div class="card stat"><div class="label">COGS</div><div class="value">${money(cogs)}</div></div><div class="card stat"><div class="label">Gross Profit</div><div class="value profit">${money(gross)}</div></div><div class="card stat"><div class="label">Net Profit</div><div class="value ${net<0?'negative':'profit'}">${money(net)}</div></div></div><div class="grid stats"><div class="card stat"><div class="label">Operating Expenses</div><div class="value">${money(exp)}</div></div><div class="card stat"><div class="label">Purchases</div><div class="value">${money(purchaseTotal())}</div></div><div class="card stat"><div class="label">Stock Value</div><div class="value">${money(stockValue())}</div></div><div class="card stat"><div class="label">Cash</div><div class="value">${money(totalCash())}</div></div></div><div class="section"><div class="card"><h2>Product-wise Report</h2><div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Stock Value</th><th>Sold</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${state.products.map(p=>{const a=state.sales.filter(s=>s.productId===p.id);return `<tr><td>${esc(p.name)}</td><td>${bn(p.stock)}</td><td>${money(p.stock*p.cost)}</td><td>${bn(sum(a,s=>s.qty))}</td><td>${money(salesTotal(a))}</td><td class="profit">${money(profitTotal(a))}</td></tr>`}).join('')||'<tr><td colspan="6">কোনো data নেই</td></tr>'}</tbody></table></div></div></div>`}
function settings(){return `<div class="card"><h2>Settings & Backup</h2><p>এই Version-এ data browser-এর Local Storage-এ থাকে। Update করার সময় একই storage key রাখা হয়েছে, তাই পুরোনো Products, Sales ও Expenses মুছে যাবে না।</p><div class="actions"><button class="btn secondary" onclick="downloadBackup()">⬇️ Backup JSON</button><label class="btn secondary" style="display:inline-block">⬆️ Restore JSON<input type="file" accept="application/json" onchange="restoreBackup(event)" style="display:none"></label></div></div><div class="card section"><h2>⚠️ Danger Zone</h2><p>সব হিসাব মুছে ফেললে ফেরত আনা যাবে না। আগে Backup নিন।</p><button class="btn danger" onclick="resetData()">সব Data মুছে ফেলুন</button></div>`}
function openModal(html){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="modalbox"><div class="modalhead"><h2>${html.title}</h2><button class="close" onclick="closeModal()">✕</button></div>${html.body}</div></div>`;document.body.appendChild(d)}
function closeModal(){document.getElementById('modal')?.remove()}
function openProduct(p={}){openModal({title:p.id?'Edit Product':'Add Product',body:`<div class="form"><div class="field"><label>Product Name</label><input id="pName" value="${esc(p.name||'')}"></div><div class="field"><label>Purchase Price / pcs</label><input id="pCost" type="number" min="0" value="${p.cost??''}"></div><div class="field"><label>Initial Stock</label><input id="pStock" type="number" min="0" value="${p.stock??0}"></div><button class="btn primary" onclick="saveProduct('${p.id||''}')">✓ SAVE PRODUCT</button></div>`})}
function saveProduct(id){const name=document.getElementById('pName').value.trim(),cost=+document.getElementById('pCost').value,stock=+document.getElementById('pStock').value;if(!name||cost<0||stock<0)return toast('সঠিক তথ্য দিন');if(id){const p=state.products.find(x=>x.id===id);p.name=name;p.cost=cost;p.stock=stock}else state.products.push({id:uid(),name,cost,stock});save();closeModal();render();toast('Product saved')}
function editProduct(id){openProduct(state.products.find(p=>p.id===id))}
function deleteProduct(id){if(state.sales.some(s=>s.productId===id)||state.purchases.some(p=>p.productId===id)){return toast('এই Product-এর history আছে, মুছবেন না।')}if(!confirm('এই Product মুছবেন?'))return;state.products=state.products.filter(p=>p.id!==id);save();render()}
function viewProduct(id){const p=state.products.find(x=>x.id===id),a=state.sales.filter(s=>s.productId===id),pu=state.purchases.filter(x=>x.productId===id);openModal({title:`📦 ${esc(p.name)}`,body:`<div class="grid stats"><div class="card stat"><div class="label">Purchase Price</div><div class="value">${money(p.cost)}</div></div><div class="card stat"><div class="label">Current Stock</div><div class="value">${bn(p.stock)} pcs</div></div><div class="card stat"><div class="label">Stock Value</div><div class="value">${money(p.stock*p.cost)}</div></div><div class="card stat"><div class="label">Total Sold</div><div class="value">${bn(sum(a,s=>s.qty))}</div></div><div class="card stat"><div class="label">Total Sales</div><div class="value">${money(salesTotal(a))}</div></div><div class="card stat"><div class="label">Total Profit</div><div class="value profit">${money(profitTotal(a))}</div></div></div><h3>Purchase History</h3>${pu.length?salesList(pu.map(x=>({productName:x.productName,qty:x.qty,price:x.price,payment:x.payment,date:x.date})).slice().reverse()):'<div class="card empty">কোনো purchase নেই।</div>'}<h3>Sales History</h3>${salesList(a.slice().reverse())}`})}
function openSale(){go('sales');setTimeout(()=>document.getElementById('salePrice')?.focus(),50)}
function saleTotalPreview(){const q=+document.getElementById('saleQty')?.value||0,p=+document.getElementById('salePrice')?.value||0;if(document.getElementById('salePreview'))document.getElementById('salePreview').textContent=money(q*p)}
function addSale(){const pid=document.getElementById('saleProduct').value,q=+document.getElementById('saleQty').value,price=+document.getElementById('salePrice').value,pay=document.getElementById('salePayment').value,p=state.products.find(x=>x.id===pid);if(!p||q<1||price<0||q>p.stock)return toast('স্টক বা তথ্য ঠিক নেই');p.stock-=q;state.sales.push({id:uid(),productId:pid,productName:p.name,cost:p.cost,qty:q,price,payment:pay,date:today()});save();render();toast('Sale saved')}
function deleteSale(id){const s=state.sales.find(x=>x.id===id);if(!s)return;if(!confirm('এই Sale মুছবেন? Stock ফিরিয়ে দেওয়া হবে।'))return;const p=state.products.find(x=>x.id===s.productId);if(p)p.stock+=s.qty;state.sales=state.sales.filter(x=>x.id!==id);save();render()}
function editSale(id){const s=state.sales.find(x=>x.id===id);openModal({title:'Edit Sale',body:`<div class="form"><div class="field"><label>Product</label><input value="${esc(s.productName)}" disabled></div><div class="field"><label>Quantity</label><input id="esQty" type="number" min="1" value="${s.qty}"></div><div class="field"><label>Selling Price / pcs</label><input id="esPrice" type="number" min="0" value="${s.price}"></div><div class="field"><label>Payment</label>${paymentSelect('esPay',s.payment)}</div><button class="btn primary" onclick="updateSale('${id}')">✓ UPDATE SALE</button></div>`})}
function updateSale(id){const s=state.sales.find(x=>x.id===id),q=+document.getElementById('esQty').value,price=+document.getElementById('esPrice').value,pay=document.getElementById('esPay').value,p=state.products.find(x=>x.id===s.productId),diff=q-s.qty;if(!p||q<1||price<0||diff>p.stock)return toast('পর্যাপ্ত stock নেই');p.stock-=diff;s.qty=q;s.price=price;s.payment=pay;save();closeModal();render();toast('Sale updated')}
function purchasePreview(){const q=+document.getElementById('purQty')?.value||0,p=+document.getElementById('purPrice')?.value||0;if(document.getElementById('purPreview'))document.getElementById('purPreview').textContent=money(q*p)}
function addPurchase(){const pid=document.getElementById('purProduct').value,q=+document.getElementById('purQty').value,price=+document.getElementById('purPrice').value,pay=document.getElementById('purPayment').value,p=state.products.find(x=>x.id===pid);if(!p||q<1||price<0)return toast('সঠিক তথ্য দিন');const oldStock=p.stock,oldCost=p.cost,totalOld=oldStock*oldCost,totalNew=q*price;p.stock=oldStock+q;p.cost=(totalOld+totalNew)/(p.stock||1);state.purchases.push({id:uid(),productId:pid,productName:p.name,qty:q,price,payment:pay,date:today()});save();render();toast('Purchase saved')}
function addExpense(){const title=document.getElementById('expTitle').value.trim(),category=document.getElementById('expCategory').value,type=document.getElementById('expType').value,amount=+document.getElementById('expAmount').value,payment=document.getElementById('expPayment').value;if(!title||amount<=0)return toast('সঠিক তথ্য দিন');state.expenses.push({id:uid(),title,category,type,amount,payment,date:today()});if(type==='asset')state.assets.push({id:uid(),title,category,amount,payment,date:today()});save();render();toast('Expense saved')}
function deleteExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;if(!confirm('এই Expense মুছবেন?'))return;state.expenses=state.expenses.filter(x=>x.id!==id);if(e.type==='asset'){const a=state.assets.find(x=>x.title===e.title&&x.amount===e.amount&&x.date===e.date&&x.payment===e.payment);if(a)state.assets=state.assets.filter(x=>x.id!==a.id)}save();render()}
function saveCapital(){const n=+document.getElementById('capitalInput').value;if(n<0)return toast('সঠিক তথ্য দিন');state.settings.capital=n;save();render();toast('Capital saved')}
function downloadBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hisab-khata-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}
function restoreBackup(ev){const file=ev.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming||!Array.isArray(incoming.products)||!Array.isArray(incoming.sales)||!Array.isArray(incoming.expenses))throw new Error();if(!confirm('Backup restore করলে বর্তমান data replace হবে। Continue?'))return;localStorage.setItem(BACKUP_KEY,JSON.stringify(state));state={...defaultState,...incoming,settings:{...defaultState.settings,...(incoming.settings||{})}};state.expenses=state.expenses.map(e=>({...e,category:e.category||'অন্যান্য',type:e.type||'operating'}));save();render();toast('Backup restored')}catch(e){toast('Backup file সঠিক নয়')}};r.readAsText(file)}
function go(p){page=p==='more'?'more':p;render()}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function resetData(){if(confirm('সব হিসাব মুছে ফেলবেন? এটি ফেরত আনা যাবে না।')){localStorage.setItem(BACKUP_KEY,JSON.stringify(state));state=JSON.parse(JSON.stringify(defaultState));save();render()}}
render();
