const KEY='hisab-khata-v1', BACKUP_KEY='hisab-khata-auto-backup-v1';
const defaultState={products:[],sales:[],expenses:[],purchases:[],assets:[],capitalAdds:[],settings:{capital:0,language:'bn',theme:'dark'}};
let raw=null; try{raw=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}
if(raw){try{localStorage.setItem(BACKUP_KEY,JSON.stringify(raw))}catch(e){}}
let state={...defaultState,...(raw||{})};
for(const k of ['products','sales','expenses','purchases','assets','capitalAdds']) state[k]=Array.isArray(state[k])?state[k]:[];
state.settings={...defaultState.settings,...(state.settings||{})};
state.expenses=state.expenses.map(e=>({...e,category:e.category||'অন্যান্য',type:e.type||'operating'}));
let page='dashboard', authMode='login', cloudBusy=false, cloudTimer=null;
const bn=n=>new Intl.NumberFormat('bn-BD',{maximumFractionDigits:2}).format(Number(n)||0);
const money=n=>'৳ '+bn(n);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const nowISO=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const sum=(arr,fn)=>arr.reduce((x,v)=>x+(Number(fn(v))||0),0);
const stamp=()=>nowISO();
function timeText(ts){if(!ts)return '';const d=new Date(ts);if(Number.isNaN(d.getTime()))return '';return d.toLocaleString(state.settings.language==='en'?'en-US':'bn-BD',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function timeMeta(ts,action='Added'){if(!ts)return '';return `<small class="timestamp">${timeText(ts)} · ${action}</small>`}
function normalizeRecord(x){const createdAt=x.createdAt||x.updatedAt||null;return {...x,createdAt,updatedAt:x.updatedAt||createdAt};}
for(const k of ['products','sales','expenses','purchases','assets','capitalAdds'])state[k]=state[k].map(normalizeRecord);
function save(local=true){if(local)localStorage.setItem(KEY,JSON.stringify(state));scheduleCloudSave()}
function scheduleCloudSave(){if(!window.HKCloud?.configured||!window.HKCloud.user)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudSave(),500)}
async function cloudSave(){if(!window.HKCloud?.user||cloudBusy)return;cloudBusy=true;setSync('syncing');try{await window.HKCloud.ready;await window.HKCloud.save(window.HKCloud.user.uid,state);setSync('synced')}catch(e){console.error(e);setSync('error')}finally{cloudBusy=false}}
function setSync(s){const el=document.getElementById('syncStatus');if(!el)return;el.className='sync '+s;el.textContent=s==='synced'?'● Synced':s==='syncing'?'↻ Syncing…':s==='error'?'! Offline':'● Local'}
async function loadCloud(){if(!window.HKCloud?.configured||!window.HKCloud.user)return;try{await window.HKCloud.ready;const cloud=await window.HKCloud.load(window.HKCloud.user.uid);if(cloud){state={...defaultState,...cloud,settings:{...defaultState.settings,...(cloud.settings||{})}};for(const k of ['products','sales','expenses','purchases','assets','capitalAdds'])state[k]=(state[k]||[]).map(normalizeRecord);localStorage.setItem(KEY,JSON.stringify(state));toast('☁️ Cloud data loaded')}else if(raw){await window.HKCloud.save(window.HKCloud.user.uid,state);toast('☁️ Local data cloud-এ backup হয়েছে')}render()}catch(e){console.error(e);toast('Cloud sync পাওয়া যায়নি')}}
const T={
 bn:{dashboard:'ড্যাশবোর্ড',sales:'বিক্রি',products:'পণ্য ও স্টক',purchases:'মাল কেনা',expenses:'খরচ',money:'টাকা',reports:'রিপোর্ট',settings:'সেটিংস',home:'হোম',stock:'স্টক',more:'আরও',welcome:'স্বাগতম',todaySales:'আজকের বিক্রি',todayGross:'আজকের গ্রস লাভ',todayNet:'আজকের নিট লাভ',totalSales:'মোট বিক্রি',grossProfit:'গ্রস লাভ',businessExpense:'ব্যবসায়িক খরচ',netProfit:'নিট লাভ',stockQty:'মোট স্টক',stockValue:'স্টকের ক্রয়মূল্য',purchasesTotal:'মাল কেনা',cash:'হাতে ব্যবসার টাকা',quick:'দ্রুত হিসাব',recent:'সাম্প্রতিক লেনদেন',addProduct:'পণ্য যোগ করুন',addSale:'বিক্রি যোগ করুন',save:'সংরক্ষণ করুন',update:'আপডেট করুন',details:'বিস্তারিত',edit:'এডিট',delete:'মুছুন',product:'পণ্য',quantity:'পরিমাণ',sellPrice:'বিক্রয় মূল্য / pcs',purchasePrice:'ক্রয় মূল্য / pcs',payment:'পেমেন্ট',total:'মোট',expenseTitle:'খরচের নাম',category:'ক্যাটাগরি',type:'ধরন',amount:'পরিমাণ',backup:'ব্যাকআপ',restore:'রিস্টোর',language:'ভাষা',appearance:'থিম',dark:'ডার্ক',light:'লাইট',system:'সিস্টেম',cloud:'ক্লাউড',login:'লগইন',logout:'লগআউট',google:'Google দিয়ে লগইন',email:'ইমেইল',password:'পাসওয়ার্ড',signup:'অ্যাকাউন্ট তৈরি করুন',signin:'লগইন করুন',local:'Local mode',synced:'Synced'},
 en:{dashboard:'Dashboard',sales:'Sales',products:'Products & Stock',purchases:'Purchases',expenses:'Expenses',money:'Money',reports:'Reports',settings:'Settings',home:'Home',stock:'Stock',more:'More',welcome:'Welcome',todaySales:"Today's Sales",todayGross:"Today's Gross Profit",todayNet:"Today's Net Profit",totalSales:'Total Sales',grossProfit:'Gross Profit',businessExpense:'Business Expense',netProfit:'Net Profit',stockQty:'Total Stock',stockValue:'Stock Value',purchasesTotal:'Purchases',cash:'Business Cash',quick:'Quick Actions',recent:'Recent Transactions',addProduct:'Add Product',addSale:'Add Sale',save:'Save',update:'Update',details:'Details',edit:'Edit',delete:'Delete',product:'Product',quantity:'Quantity',sellPrice:'Selling Price / pcs',purchasePrice:'Purchase Price / pcs',payment:'Payment',total:'Total',expenseTitle:'Expense Title',category:'Category',type:'Type',amount:'Amount',backup:'Backup',restore:'Restore',language:'Language',appearance:'Appearance',dark:'Dark',light:'Light',system:'System',cloud:'Cloud',login:'Login',logout:'Log out',google:'Continue with Google',email:'Email',password:'Password',signup:'Create account',signin:'Sign in',local:'Local mode',synced:'Synced'}
};
const t=k=>(T[state.settings.language]||T.bn)[k]||k;
function applyTheme(){document.documentElement.dataset.theme=state.settings.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.settings.theme;document.documentElement.lang=state.settings.language==='en'?'en':'bn'}
function salesTotal(a=state.sales){return sum(a,s=>s.qty*s.price)}
function cogsTotal(a=state.sales){return sum(a,s=>s.qty*s.cost)}
function profitTotal(a=state.sales){return salesTotal(a)-cogsTotal(a)}
function expenseTotal(a=state.expenses){return sum(a,e=>e.type==='asset'?0:e.amount)}
function todaySales(){return state.sales.filter(s=>s.date===today())}
function todayExpenses(){return state.expenses.filter(e=>e.date===today()&&e.type!=='asset')}
function todayGrossProfit(){const a=todaySales();return salesTotal(a)-cogsTotal(a)}
function todayNetProfit(){return todayGrossProfit()-expenseTotal(todayExpenses())}
function cashOutflowExpenses(a=state.expenses){return sum(a,e=>e.amount)}
function purchaseTotal(a=state.purchases){return sum(a,p=>p.qty*p.price)}
function stockQty(){return sum(state.products,p=>p.stock)}
function stockValue(){return sum(state.products,p=>p.stock*p.cost)}
function openingStockValue(){return sum(state.products,p=>Number(p.openingStockQty||0)*Number(p.openingCost??p.cost??0))}
function initialCapital(){return (Number(state.settings.capital)||0)+openingStockValue()}
function additionalCapital(){return sum(state.capitalAdds,c=>c.amount)}
function netProfit(){return profitTotal()-expenseTotal()}
function currentCapital(){return totalBusinessValue()}
function accountBalance(account){const initialCash=Number(state.settings.capital)||0;const added=sum(state.capitalAdds,c=>c.payment===account?c.amount:0);const sales=sum(state.sales,s=>s.payment===account?s.qty*s.price:0);const exp=sum(state.expenses,e=>e.payment===account?e.amount:0);const pur=sum(state.purchases,p=>p.payment===account?p.qty*p.price:0);const assets=sum(state.assets,a=>a.payment===account?a.amount:0);return (account==='Cash'?initialCash:0)+added+sales-exp-pur-assets}
function totalCash(){return ['Cash','bKash','Nagad','Bank'].reduce((x,a)=>x+accountBalance(a),0)}
function totalBusinessValue(){return totalCash()+stockValue()}
function render(){applyTheme();document.getElementById('app').innerHTML=`<div class="app"><div class="layout"><aside class="sidebar"><div class="brand"><span class="brandmark">৳</span><div><b>হিসাব খাতা</b><small>Business Ledger</small></div></div>${nav('dashboard','⌂',t('dashboard'))}${nav('sales','↗',t('sales'))}${nav('products','▦',t('products'))}${nav('purchases','＋',t('purchases'))}${nav('expenses','−',t('expenses'))}${nav('money','৳',t('money'))}${nav('reports','◔',t('reports'))}<div class="sidebottom">${nav('settings','⚙',t('settings'))}</div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">${page==='dashboard'?t('welcome'):'হিসাব খাতা'}</div><h1>${title()}</h1></div><div class="top-actions"><span id="syncStatus" class="sync">${window.HKCloud?.configured?'● Cloud':'● Local'}</span><button class="iconbtn" onclick="toggleTheme()">${document.documentElement.dataset.theme==='dark'?'☀':'☾'}</button><button class="avatar" onclick="go('settings')">${window.HKCloud?.user?.displayName?.[0]||'R'}</button></div></div>${window.HKCloud?.configured&&!window.HKCloud.user?loginView():content()}</main></div><button class="fab" onclick="openSale()"><span>＋</span>${t('addSale')}</button><nav class="bottom">${navb('dashboard','⌂',t('home'))}${navb('sales','↗',t('sales'))}${navb('products','▦',t('stock'))}${navb('more','⋯',t('more'))}</nav></div>`;setSync(window.HKCloud?.user?'synced':'local')}
function nav(p,i,x){return `<button class="navbtn ${page===p?'active':''}" onclick="go('${p}')"><span>${i}</span>${x}</button>`}
function navb(p,i,x){return `<button class="${page===p?'active':''}" onclick="go('${p}')"><span>${i}</span>${x}</button>`}
function title(){return ({dashboard:t('dashboard'),sales:t('sales'),products:t('products'),purchases:t('purchases'),expenses:t('expenses'),money:t('money'),reports:t('reports'),settings:t('settings'),more:t('more')})[page]||'হিসাব খাতা'}
function loginView(){return `<div class="login-shell"><div class="login-card"><div class="brand center"><span class="brandmark">৳</span><div><b>হিসাব খাতা</b><small>Premium Business Ledger</small></div></div><h2>${authMode==='login'?t('signin'):t('signup')}</h2><p class="muted">${authMode==='login'?'আপনার ব্যবসার হিসাব Cloud-এ নিরাপদে sync করুন।':'একটি account তৈরি করে সব device-এ হিসাব ব্যবহার করুন।'}</p><button class="google" onclick="googleLogin()">G &nbsp; ${t('google')}</button><div class="or"><span>or</span></div><div class="form"><div class="field"><label>${t('email')}</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field"><label>${t('password')}</label><input id="authPassword" type="password" autocomplete="current-password"></div><button class="btn primary" onclick="emailAuth()">${authMode==='login'?t('signin'):t('signup')}</button></div><button class="linkbtn" onclick="authMode=authMode==='login'?'signup':'login';render()">${authMode==='login'?t('signup'):t('signin')}</button><p class="tiny">Firebase config না দিলে app Local mode-এও কাজ করবে।</p></div></div>`}
function content(){if(page==='dashboard')return dashboard();if(page==='sales')return sales();if(page==='products')return products();if(page==='purchases')return purchases();if(page==='expenses')return expenses();if(page==='money')return moneyPage();if(page==='reports')return reports();return settings()}
function dashboard(){const ts=todaySales(),gross=profitTotal(),op=expenseTotal(),net=gross-op,todayGross=todayGrossProfit(),todayNet=todayNetProfit();return `<div class="today-grid"><div class="today-card"><div class="today-icon">↗</div><div class="hero-kicker">${t('todaySales')}</div><div class="today-money">${money(salesTotal(ts))}</div><div class="hero-meta">${bn(sum(ts,s=>s.qty))} pcs sold</div></div><div class="today-card"><div class="today-icon">↗</div><div class="hero-kicker">${t('todayGross')}</div><div class="today-money">${money(todayGross)}</div><div class="hero-meta">Sales − Cost</div></div><div class="today-card"><div class="today-icon">৳</div><div class="hero-kicker">${t('todayNet')}</div><div class="today-money ${todayNet<0?'negative':''}">${money(todayNet)}</div><div class="hero-meta">Gross − Expense</div></div></div><div class="quick"><button onclick="openSale()">↗<span>${t('addSale')}</span></button><button onclick="openProduct()">＋<span>${t('addProduct')}</span></button><button onclick="go('purchases')">▦<span>${t('purchases')}</span></button><button onclick="go('expenses')">−<span>${t('expenses')}</span></button></div><div class="stats-grid"><div class="metric"><small>${t('totalSales')}</small><strong>${money(salesTotal())}</strong><span class="up">Business</span></div><div class="metric"><small>${t('grossProfit')}</small><strong>${money(gross)}</strong><span class="up">Profit</span></div><div class="metric"><small>${t('businessExpense')}</small><strong>${money(op)}</strong><span>Operating</span></div><div class="metric"><small>${t('netProfit')}</small><strong class="${net<0?'negative':'profit'}">${money(net)}</strong><span>Net</span></div></div><div class="stats-grid compact"><div class="metric"><small>Current Capital</small><strong>${money(currentCapital())}</strong><span>Auto calculated</span></div><div class="metric"><small>Total Business Value</small><strong>${money(totalBusinessValue())}</strong><span>Cash + Stock</span></div><div class="metric"><small>${t('stockValue')}</small><strong>${money(stockValue())}</strong><span>${bn(stockQty())} pcs</span></div><div class="metric"><small>${t('cash')}</small><strong>${money(totalCash())}</strong><span>Cash + bKash + Nagad + Bank</span></div></div><section class="section"><div class="sectionhead"><div><span class="eyebrow">LIVE</span><h2>${t('recent')}</h2></div><button class="ghost" onclick="go('sales')">→</button></div>${salesList(state.sales.slice().reverse().slice(0,5))}</section>`}
function sales(){const ts=state.sales.filter(s=>s.date===today());return `<section class="hero small"><div><div class="hero-kicker">${t('todaySales')}</div><div class="hero-money">${money(salesTotal(ts))}</div><div class="hero-meta">${bn(sum(ts,s=>s.qty))} pcs sold</div></div></section><section class="section"><div class="sectionhead"><h2>${t('addSale')}</h2></div><div class="card form"><div class="field"><label>${t('product')}</label><select id="saleProduct">${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${bn(p.stock)} pcs</option>`).join('')}</select></div><div class="two-fields"><div class="field"><label>${t('quantity')}</label><input id="saleQty" type="number" min="1" value="1" oninput="saleTotalPreview()"></div><div class="field"><label>${t('sellPrice')}</label><input id="salePrice" type="number" min="0" step="0.01" value="0" oninput="saleTotalPreview()"></div></div><div class="totalrow"><span>${t('total')}</span><b id="salePreview">৳ 0</b></div><div class="field"><label>${t('payment')}</label>${paymentSelect('salePayment')}</div><button class="btn primary wide" onclick="addSale()" ${state.products.length?'':'disabled'}>${t('save')}</button>${state.products.length?'':'<div class="muted">আগে একটি Product যোগ করুন।</div>'}</div></section><section class="section"><div class="sectionhead"><h2>${state.settings.language==='en'?"Today's Sales":'আজকের বিক্রি'}</h2></div>${salesList(ts.slice().reverse())}</section>`}
function paymentSelect(id,value='Cash'){return `<select id="${id}">${['Cash','bKash','Nagad','Bank'].map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select>`}
function salesList(arr){if(!arr.length)return '<div class="card empty">আজ এখনো কোনো বিক্রি নেই।</div>';return `<div class="list">${arr.map(s=>`<div class="item"><div class="item-icon sale">↗</div><div class="item-main"><h3>${esc(s.productName)}</h3><p>${bn(s.qty)} pcs × ${money(s.price)} · ${esc(s.payment)}</p>${timeMeta(s.updatedAt||s.createdAt,s.updatedAt&&s.updatedAt!==s.createdAt?'Updated':'Sold')}</div><div class="item-right"><strong>${money(s.qty*s.price)}</strong><div class="actions"><button class="mini" onclick="editSale('${s.id}')">✎</button><button class="mini danger" onclick="deleteSale('${s.id}')">×</button></div></div></div>`).join('')}</div>`}
function products(){return `<section class="hero small"><div><div class="hero-kicker">${t('stockValue')}</div><div class="hero-money">${money(stockValue())}</div><div class="hero-meta">${bn(stockQty())} pcs</div></div></section><div class="sectionhead"><h2>${t('products')}</h2><button class="btn primary" onclick="openProduct()">＋ ${t('addProduct')}</button></div>${!state.products.length?'<div class="card empty">কোনো পণ্য নেই।</div>':`<div class="list">${state.products.map(p=>`<div class="item"><div class="item-icon product">▦</div><div class="item-main"><h3>${esc(p.name)}</h3><p>${t('purchasePrice')}: ${money(p.cost)}</p><p>${t('stockQty')}: <span class="${p.stock<=5?'low':''}">${bn(p.stock)} pcs</span></p>${timeMeta(p.updatedAt||p.createdAt,p.updatedAt&&p.updatedAt!==p.createdAt?'Updated':'Added')}</div><div class="item-right"><strong>${money(p.stock*p.cost)}</strong><div class="actions"><button class="mini" onclick="viewProduct('${p.id}')">${t('details')}</button><button class="mini" onclick="editProduct('${p.id}')">✎</button><button class="mini danger" onclick="deleteProduct('${p.id}')">×</button></div></div></div>`).join('')}</div>`}`}
function purchases(){return `<section class="hero small"><div><div class="hero-kicker">${t('purchasesTotal')}</div><div class="hero-money">${money(purchaseTotal())}</div><div class="hero-meta">${state.purchases.length} records</div></div></section><section class="section"><div class="sectionhead"><h2>${t('purchases')}</h2></div><div class="card form"><div class="field"><label>${t('product')}</label><select id="purProduct">${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${bn(p.stock)} pcs</option>`).join('')}</select></div><div class="two-fields"><div class="field"><label>${t('quantity')}</label><input id="purQty" type="number" min="1" value="1" oninput="purchasePreview()"></div><div class="field"><label>${t('purchasePrice')}</label><input id="purPrice" type="number" min="0" step="0.01" value="0" oninput="purchasePreview()"></div></div><div class="totalrow"><span>${t('total')}</span><b id="purPreview">৳ 0</b></div><div class="field"><label>${t('payment')}</label>${paymentSelect('purPayment')}</div><button class="btn primary wide" onclick="addPurchase()">${t('save')}</button></div></section><section class="section"><h2>Purchase History</h2>${state.purchases.length?`<div class="list">${state.purchases.slice().reverse().map(p=>`<div class="item"><div class="item-icon purchase">＋</div><div class="item-main"><h3>${esc(p.productName)}</h3><p>${bn(p.qty)} pcs × ${money(p.price)} · ${esc(p.payment)}</p>${timeMeta(p.updatedAt||p.createdAt,'Purchased')}</div><div class="item-right"><strong>${money(p.qty*p.price)}</strong></div></div>`).join('')}</div>`:'<div class="card empty">কোনো purchase record নেই।</div>'}</section>`}
function expenses(){return `<section class="section"><div class="sectionhead"><h2>${t('expenses')}</h2></div><div class="card form"><div class="field"><label>${t('expenseTitle')}</label><input id="expTitle"></div><div class="two-fields"><div class="field"><label>${t('category')}</label><select id="expCategory">${['যাতায়াত','দোকান ভাড়া','সরঞ্জাম','Packaging','Marketing','খাবার','Delivery','Utility','Communication','অন্যান্য'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>${t('type')}</label><select id="expType"><option value="operating">Business Expense</option><option value="asset">Asset / Equipment</option></select></div></div><div class="field"><label>${t('amount')}</label><input id="expAmount" type="number" min="0" step="0.01"></div><div class="field"><label>${t('payment')}</label>${paymentSelect('expPayment')}</div><button class="btn primary wide" onclick="addExpense()">${t('save')}</button></div></section><section class="section"><div class="list">${state.expenses.slice().reverse().map(e=>`<div class="item"><div class="item-icon expense">−</div><div class="item-main"><h3>${esc(e.title)}</h3><p>${esc(e.category)} · ${esc(e.payment)} · ${e.type==='asset'?'Asset':'Business Expense'}</p>${timeMeta(e.updatedAt||e.createdAt,'Added')}</div><div class="item-right"><strong>${money(e.amount)}</strong><button class="mini danger" onclick="deleteExpense('${e.id}')">×</button></div></div>`).join('')||'<div class="card empty">কোনো expense নেই।</div>'}</div></section>`}
function moneyPage(){return `<section class="hero"><div><div class="hero-kicker">Total Business Value</div><div class="hero-money">${money(totalBusinessValue())}</div><div class="hero-meta">Cash + bKash + Nagad + Bank + Stock</div></div></section><div class="stats-grid compact"><div class="metric"><small>Current Capital</small><strong>${money(currentCapital())}</strong><span>Initial + Added + Net Profit</span></div><div class="metric"><small>Invested Capital</small><strong>${money(initialCapital()+additionalCapital())}</strong></div><div class="metric"><small>Net Profit</small><strong class="profit">${money(netProfit())}</strong></div><div class="metric"><small>Stock Value</small><strong>${money(stockValue())}</strong></div></div><div class="stats-grid compact">${['Cash','bKash','Nagad','Bank'].map(a=>`<div class="metric"><small>${a}</small><strong>${money(accountBalance(a))}</strong></div>`).join('')}</div><section class="section"><div class="card form"><h2>Initial Capital</h2><p class="muted">ব্যবসা শুরুর Cash Capital। বর্তমান Capital অটো হিসাব হবে।</p><div class="field"><label>Opening Cash</label><input id="capitalInput" type="number" min="0" value="${state.settings.capital||0}"></div><button class="btn secondary wide" onclick="saveCapital()">Save Initial Capital</button></div><div class="card form"><h2>＋ Add More Capital</h2><div class="two-fields"><div class="field"><label>Amount</label><input id="addCapAmount" type="number" min="0" step="0.01"></div><div class="field"><label>Payment</label>${paymentSelect('addCapPayment')}</div></div><button class="btn primary wide" onclick="addCapital()">Add Capital</button></div><div class="card"><h2>Capital History</h2>${state.capitalAdds.length?state.capitalAdds.slice().reverse().map(c=>`<div class="item"><div class="item-main"><h3>${money(c.amount)}</h3><p>${esc(c.payment)}</p>${timeMeta(c.createdAt,'Added Capital')}</div><button class="mini danger" onclick="deleteCapital('${c.id}')">×</button></div>`).join(''):'<div class="empty">কোনো Additional Capital নেই।</div>'}</div></section>`}
function reports(){const salesv=salesTotal(),cogs=cogsTotal(),gross=profitTotal(),exp=expenseTotal(),net=gross-exp;return `<div class="stats-grid"><div class="metric"><small>Sales</small><strong>${money(salesv)}</strong></div><div class="metric"><small>COGS</small><strong>${money(cogs)}</strong></div><div class="metric"><small>Gross Profit</small><strong>${money(gross)}</strong></div><div class="metric"><small>Net Profit</small><strong class="${net<0?'negative':'profit'}">${money(net)}</strong></div></div><section class="section"><div class="card"><h2>Product-wise Report</h2><div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Stock Value</th><th>Sold</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${state.products.map(p=>{const a=state.sales.filter(s=>s.productId===p.id);return `<tr><td>${esc(p.name)}</td><td>${bn(p.stock)}</td><td>${money(p.stock*p.cost)}</td><td>${bn(sum(a,s=>s.qty))}</td><td>${money(salesTotal(a))}</td><td class="profit">${money(profitTotal(a))}</td></tr>`}).join('')||'<tr><td colspan="6">কোনো data নেই</td></tr>'}</tbody></table></div></div></section>`}
function settings(){const user=window.HKCloud?.user;return `<section class="settings-grid"><div class="card"><div class="sectionhead"><div><span class="eyebrow">${t('cloud')}</span><h2>${user?esc(user.email||'Google Account'):'Local mode'}</h2></div><span class="status-dot ${user?'on':''}"></span></div>${window.HKCloud?.configured?(user?`<p class="muted">Cloud sync চালু আছে। এই device-এর হিসাব Firebase Cloud-এর সঙ্গে sync হবে।</p><button class="btn secondary wide" onclick="logout()">${t('logout')}</button>`:`<p class="muted">Login করলে একই হিসাব একাধিক device-এ ব্যবহার করতে পারবেন।</p><button class="btn primary wide" onclick="render()">${t('login')}</button>`):`<p class="muted">Firebase config এখনো যোগ করা হয়নি। Local data ঠিকমতো চলবে; config যোগ করলে Login + Cloud Sync চালু হবে।</p>`}</div><div class="card"><span class="eyebrow">${t('appearance')}</span><h2>${t('appearance')}</h2><div class="seg"><button class="${state.settings.theme==='dark'?'active':''}" onclick="setTheme('dark')">☾ ${t('dark')}</button><button class="${state.settings.theme==='light'?'active':''}" onclick="setTheme('light')">☀ ${t('light')}</button><button class="${state.settings.theme==='system'?'active':''}" onclick="setTheme('system')">◐ ${t('system')}</button></div></div><div class="card"><span class="eyebrow">${t('language')}</span><h2>${t('language')}</h2><div class="seg"><button class="${state.settings.language==='bn'?'active':''}" onclick="setLang('bn')">বাংলা</button><button class="${state.settings.language==='en'?'active':''}" onclick="setLang('en')">English</button></div></div><div class="card"><span class="eyebrow">BACKUP</span><h2>Backup & Restore</h2><div class="actions wrap"><button class="btn secondary" onclick="downloadBackup()">↓ ${t('backup')}</button><label class="btn secondary">↑ ${t('restore')}<input type="file" accept="application/json" onchange="restoreBackup(event)" hidden></label></div><p class="tiny">বর্তমান Local backup একই storage key-তে রাখা হয়েছে।</p></div><div class="card danger-card"><h2>Danger Zone</h2><p class="muted">সব হিসাব মুছে ফেলার আগে Backup নিন।</p><button class="btn danger wide" onclick="resetData()">সব Data মুছে ফেলুন</button></div></section>`}
function openModal(x){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="modalbox"><div class="modalhead"><h2>${x.title}</h2><button class="close" onclick="closeModal()">×</button></div>${x.body}</div></div>`;document.body.appendChild(d)}
function closeModal(){document.getElementById('modal')?.remove()}
function openProduct(p={}){openModal({title:p.id?`${t('edit')}: ${esc(p.name)}`:t('addProduct'),body:`<div class="form"><div class="field"><label>${t('product')}</label><input id="pName" value="${esc(p.name||'')}"></div><div class="two-fields"><div class="field"><label>${t('purchasePrice')}</label><input id="pCost" type="number" min="0" value="${p.cost??''}"></div><div class="field"><label>${t('stockQty')}</label><input id="pStock" type="number" min="0" value="${p.stock??0}"></div></div>${!p.id?'<p class="tiny">নতুন পণ্যের এই Stock-কে Opening Stock হিসেবে ধরা হবে।</p>':''}<button class="btn primary wide" onclick="saveProduct('${p.id||''}')">${p.id?t('update'):t('save')}</button></div>`})}
function saveProduct(id){const name=document.getElementById('pName').value.trim(),cost=+document.getElementById('pCost').value,stock=+document.getElementById('pStock').value;if(!name||cost<0||stock<0)return toast('সঠিক তথ্য দিন');const ts=stamp();if(id){const p=state.products.find(x=>x.id===id);p.name=name;p.cost=cost;p.stock=stock;p.updatedAt=ts}else state.products.push({id:uid(),name,cost,stock,openingStockQty:stock,openingCost:cost,createdAt:ts,updatedAt:ts});save();closeModal();render();toast('Product saved')}
function editProduct(id){openProduct(state.products.find(p=>p.id===id))}
function deleteProduct(id){if(state.sales.some(s=>s.productId===id)||state.purchases.some(p=>p.productId===id))return toast('এই Product-এর history আছে, মুছবেন না।');if(!confirm('এই Product মুছবেন?'))return;state.products=state.products.filter(p=>p.id!==id);save();render()}
function viewProduct(id){const p=state.products.find(x=>x.id===id),a=state.sales.filter(s=>s.productId===id),pu=state.purchases.filter(x=>x.productId===id);openModal({title:`▦ ${esc(p.name)}`,body:`<div class="stats-grid compact"><div class="metric"><small>Purchase Price</small><strong>${money(p.cost)}</strong></div><div class="metric"><small>Current Stock</small><strong>${bn(p.stock)}</strong></div><div class="metric"><small>Stock Value</small><strong>${money(p.stock*p.cost)}</strong></div><div class="metric"><small>Total Sold</small><strong>${bn(sum(a,s=>s.qty))}</strong></div></div><div class="section"><h3>Created</h3>${timeMeta(p.createdAt,'Added')} · ${timeText(p.createdAt)}</div><div class="section"><h3>Sales History</h3>${salesList(a.slice().reverse())}</div><div class="section"><h3>Purchase History</h3>${pu.length?pu.slice().reverse().map(x=>`<div class="item"><div class="item-main"><h3>${bn(x.qty)} pcs</h3><p>${money(x.price)} · ${esc(x.payment)}</p>${timeMeta(x.createdAt,'Purchased')}</div><strong>${money(x.qty*x.price)}</strong></div>`).join(''):'<div class="empty">কোনো purchase নেই।</div>'}</div>`})}
function openSale(){go('sales');setTimeout(()=>document.getElementById('salePrice')?.focus(),50)}
function saleTotalPreview(){const q=+document.getElementById('saleQty')?.value||0,p=+document.getElementById('salePrice')?.value||0;if(document.getElementById('salePreview'))document.getElementById('salePreview').textContent=money(q*p)}
function addSale(){const pid=document.getElementById('saleProduct').value,q=+document.getElementById('saleQty').value,price=+document.getElementById('salePrice').value,pay=document.getElementById('salePayment').value,p=state.products.find(x=>x.id===pid);if(!p||q<1||price<0||q>p.stock)return toast('স্টক বা তথ্য ঠিক নেই');const ts=stamp();p.stock-=q;p.updatedAt=ts;state.sales.push({id:uid(),productId:pid,productName:p.name,cost:p.cost,qty:q,price,payment:pay,date:today(),createdAt:ts,updatedAt:ts});save();render();toast('Sale saved')}
function deleteSale(id){const s=state.sales.find(x=>x.id===id);if(!s)return;if(!confirm('এই Sale মুছবেন? Stock ফিরিয়ে দেওয়া হবে।'))return;const p=state.products.find(x=>x.id===s.productId);if(p){p.stock+=s.qty;p.updatedAt=stamp()}state.sales=state.sales.filter(x=>x.id!==id);save();render()}
function editSale(id){const s=state.sales.find(x=>x.id===id);openModal({title:`${t('edit')}: ${esc(s.productName)}`,body:`<div class="form"><div class="field"><label>${t('product')}</label><input value="${esc(s.productName)}" disabled></div><div class="two-fields"><div class="field"><label>${t('quantity')}</label><input id="esQty" type="number" min="1" value="${s.qty}"></div><div class="field"><label>${t('sellPrice')}</label><input id="esPrice" type="number" min="0" value="${s.price}"></div></div><div class="field"><label>${t('payment')}</label>${paymentSelect('esPay',s.payment)}</div><button class="btn primary wide" onclick="updateSale('${id}')">${t('update')}</button>${timeMeta(s.updatedAt||s.createdAt,'Updated')}</div>`})}
function updateSale(id){const s=state.sales.find(x=>x.id===id),q=+document.getElementById('esQty').value,price=+document.getElementById('esPrice').value,pay=document.getElementById('esPay').value,p=state.products.find(x=>x.id===s.productId),diff=q-s.qty;if(!p||q<1||price<0||diff>p.stock)return toast('পর্যাপ্ত stock নেই');p.stock-=diff;p.updatedAt=stamp();s.qty=q;s.price=price;s.payment=pay;s.updatedAt=stamp();save();closeModal();render();toast('Sale updated')}
function purchasePreview(){const q=+document.getElementById('purQty')?.value||0,p=+document.getElementById('purPrice')?.value||0;if(document.getElementById('purPreview'))document.getElementById('purPreview').textContent=money(q*p)}
function addPurchase(){const pid=document.getElementById('purProduct').value,q=+document.getElementById('purQty').value,price=+document.getElementById('purPrice').value,pay=document.getElementById('purPayment').value,p=state.products.find(x=>x.id===pid);if(!p||q<1||price<0)return toast('সঠিক তথ্য দিন');const ts=stamp(),oldStock=p.stock,oldCost=p.cost,totalOld=oldStock*oldCost,totalNew=q*price;p.stock=oldStock+q;p.cost=(totalOld+totalNew)/(p.stock||1);p.updatedAt=ts;state.purchases.push({id:uid(),productId:pid,productName:p.name,qty:q,price,payment:pay,date:today(),createdAt:ts,updatedAt:ts});save();render();toast('Purchase saved')}
function addExpense(){const title=document.getElementById('expTitle').value.trim(),category=document.getElementById('expCategory').value,type=document.getElementById('expType').value,amount=+document.getElementById('expAmount').value,payment=document.getElementById('expPayment').value;if(!title||amount<=0)return toast('সঠিক তথ্য দিন');const ts=stamp();state.expenses.push({id:uid(),title,category,type,amount,payment,date:today(),createdAt:ts,updatedAt:ts});if(type==='asset')state.assets.push({id:uid(),title,category,amount,payment,date:today(),createdAt:ts,updatedAt:ts});save();render();toast('Expense saved')}
function deleteExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;if(!confirm('এই Expense মুছবেন?'))return;state.expenses=state.expenses.filter(x=>x.id!==id);if(e.type==='asset'){const a=state.assets.find(x=>x.title===e.title&&x.amount===e.amount&&x.date===e.date&&x.payment===e.payment);if(a)state.assets=state.assets.filter(x=>x.id!==a.id)}save();render()}
function saveCapital(){const n=+document.getElementById('capitalInput').value;if(n<0)return toast('সঠিক তথ্য দিন');state.settings.capital=n;save();render();toast('Capital saved')}
function addCapital(){const amount=+document.getElementById('addCapAmount').value,payment=document.getElementById('addCapPayment').value;if(amount<=0)return toast('সঠিক amount দিন');const ts=stamp();state.capitalAdds.push({id:uid(),amount,payment,date:today(),createdAt:ts,updatedAt:ts});save();render();toast('Additional Capital added')}
function deleteCapital(id){const c=state.capitalAdds.find(x=>x.id===id);if(!c)return;if(!confirm('এই Additional Capital মুছবেন?'))return;state.capitalAdds=state.capitalAdds.filter(x=>x.id!==id);save();render()}
function downloadBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hisab-khata-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}
function restoreBackup(ev){const file=ev.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming||!Array.isArray(incoming.products)||!Array.isArray(incoming.sales)||!Array.isArray(incoming.expenses))throw new Error();if(!confirm('Backup restore করলে বর্তমান data replace হবে। Continue?'))return;localStorage.setItem(BACKUP_KEY,JSON.stringify(state));state={...defaultState,...incoming,settings:{...defaultState.settings,...(incoming.settings||{})}};for(const k of ['products','sales','expenses','purchases','assets','capitalAdds'])state[k]=(state[k]||[]).map(normalizeRecord);save();render();toast('Backup restored')}catch(e){toast('Backup file সঠিক নয়')}};r.readAsText(file)}
function setLang(x){state.settings.language=x;save();render()}
function setTheme(x){state.settings.theme=x;save();render()}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}
function go(p){page=p==='more'?'settings':p;render()}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1900)}
function resetData(){if(confirm('সব হিসাব মুছে ফেলবেন? এটি ফেরত আনা যাবে না.')){localStorage.setItem(BACKUP_KEY,JSON.stringify(state));state=JSON.parse(JSON.stringify(defaultState));save();render()}}
async function googleLogin(){try{await window.HKCloud.ready;const provider=new window.HKCloud.GoogleAuthProvider();await window.HKCloud.signInWithPopup(window.HKCloud.auth,provider)}catch(e){toast(e?.message||'Google login failed')}}
async function emailAuth(){try{await window.HKCloud.ready;const email=document.getElementById('authEmail').value.trim(),pass=document.getElementById('authPassword').value;if(!email||pass.length<6)return toast('Email ও কমপক্ষে 6 অক্ষরের password দিন');if(authMode==='login')await window.HKCloud.signInWithEmailAndPassword(window.HKCloud.auth,email,pass);else await window.HKCloud.createUserWithEmailAndPassword(window.HKCloud.auth,email,pass)}catch(e){toast(e?.message||'Authentication failed')}}
async function logout(){await window.HKCloud.signOut(window.HKCloud.auth)}
window.addEventListener('hk-auth',async e=>{if(e.detail){await loadCloud()}render()});
window.addEventListener('load',()=>{window.HKCloud?.ready?.then(()=>render());render()});
render();
