const KEY='hisab-khata-v1';
const defaultState={products:[],sales:[],expenses:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaultState;let page='dashboard';
const bn=n=>new Intl.NumberFormat('bn-BD',{maximumFractionDigits:2}).format(Number(n)||0);const money=n=>'৳ '+bn(n);const today=()=>new Date().toISOString().slice(0,10);const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function salesTotal(a=state.sales){return a.reduce((x,s)=>x+s.qty*s.price,0)}function profitTotal(a=state.sales){return a.reduce((x,s)=>x+s.qty*s.price-x*s.qty*s.cost,0)}
function stockValue(){return state.products.reduce((x,p)=>x+p.stock*p.cost,0)}function totalSold(){return state.sales.reduce((x,s)=>x+s.qty,0)}
function render(){document.getElementById('app').innerHTML=`<div class="app"><div class="layout"><aside class="sidebar"><div class="brand">📒 হিসাব খাতা</div>${nav('dashboard','🏠','Dashboard')}${nav('sales','💰','Sales')}${nav('products','📦','Products / Stock')}${nav('expenses','💸','Expenses')}${nav('reports','📊','Reports')}<div style="margin-top:25px">${nav('settings','⚙️','Settings')}</div></aside><main class="main"><div class="topbar"><div><h1>${title()}</h1><div class="label">সহজে হিসাব রাখুন, দ্রুত সিদ্ধান্ত নিন</div></div><button class="iconbtn" onclick="resetData()">↻</button></div>${content()}</main></div><button class="fab" onclick="openSale()">＋ Sale</button><nav class="bottom">${navb('dashboard','🏠','Home')}${navb('sales','💰','Sales')}${navb('products','📦','Stock')}${navb('more','⋯','More')}</nav></div>`}
function nav(p,i,t){return `<button class="navbtn ${page===p?'active':''}" onclick="go('${p}')">${i} &nbsp; ${t}</button>`}function navb(p,i,t){return `<button class="${page===p?'active':''}" onclick="go('${p}')">${i}<br>${t}</button>`}
function title(){return ({dashboard:'Dashboard',sales:'Sales',products:'Products / Stock',expenses:'Expenses',reports:'Reports',settings:'Settings',more:'More'})[page]||'হিসাব খাতা'}
function content(){if(page==='dashboard')return dashboard();if(page==='sales')return sales();if(page==='products')return products();if(page==='expenses')return expenses();if(page==='reports')return reports();if(page==='settings'||page==='more')return settings();return dashboard()}
function dashboard(){const ts=state.sales.filter(s=>s.date===today()),te=state.expenses.filter(e=>e.date===today());return `<div class="card hero"><div class="label">আজকের বিক্রি</div><div class="money">${money(salesTotal(ts))}</div><div>${bn(ts.reduce((x,s)=>x+s.qty,0))} pcs sold</div></div><div class="grid stats"><div class="card stat"><div class="label">মোট বিক্রি</div><div class="value">${money(salesTotal())}</div></div><div class="card stat"><div class="label">মোট লাভ</div><div class="value profit">${money(profitTotal())}</div></div><div class="card stat"><div class="label">মোট খরচ</div><div class="value">${money(salesTotal(te))}</div></div><div class="card stat"><div class="label">স্টক</div><div class="value">${bn(state.products.reduce((x,p)=>x+p.stock,0))} pcs</div></div></div><div class="section"><div class="sectionhead"><h2>Business Money</h2></div><div class="card"><div class="money">${money(salesTotal()-state.expenses.reduce((x,e)=>x+e.amount,0))}</div><div class="label">Sales Income + ${money(salesTotal())} &nbsp; • &nbsp; Expenses − ${money(state.expenses.reduce((x,e)=>x+e.amount,0))}</div></div></div><div class="section"><div class="sectionhead"><h2>সাম্প্রতিক বিক্রি</h2><button class="btn secondary" onclick="go('sales')">সব দেখুন →</button></div>${salesList(state.sales.slice().reverse().slice(0,5))}</div>`}
function sales(){const ts=state.sales.filter(s=>s.date===today());return `<div class="card hero"><div class="label">Today's Sales</div><div class="money">${money(salesTotal(ts))}</div><div>${bn(ts.reduce((x,s)=>x+s.qty,0))} pcs sold</div></div><div class="section"><div class="sectionhead"><h2>➕ Add Sale</h2></div><div class="card form"><div class="field"><label>Product</label><select id="saleProduct" onchange="saleTotalPreview()">${state.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${bn(p.stock)} pcs</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="saleQty" type="number" min="1" value="1" oninput="saleTotalPreview()"></div><div class="field"><label>Selling Price / pcs</label><input id="salePrice" type="number" min="0" step="0.01" value="0" oninput="saleTotalPreview()"></div><div class="totalrow"><span>Total Sale</span><span id="salePreview">৳ 0</span></div><div class="field"><label>Payment</label><select id="salePayment"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Bank</option></select></div><button class="btn primary" onclick="addSale()" ${state.products.length?'':'disabled'}>✓ SAVE SALE</button>${state.products.length?'':'<div class="label">আগে Products / Stock থেকে অন্তত একটি পণ্য যোগ করুন।</div>'}</div></div><div class="section"><div class="sectionhead"><h2>TODAY'S SALES</h2></div>${salesList(ts.slice().reverse())}</div>`}
function salesList(arr){if(!arr.length)return '<div class="card empty">আজ এখনো কোনো বিক্রি নেই।</div>';return `<div class="list">${arr.map(s=>`<div class="item"><div><h3>🛍️ ${esc(s.productName)}</h3><p>${bn(s.qty)} pcs × ${money(s.price)} · ${esc(s.payment)} · ${s.date}</p></div><div style="text-align:right"><strong>${money(s.qty*s.price)}</strong><div class="actions"><button class="mini" onclick="editSale('${s.id}')">✏️</button><button class="mini danger" onclick="deleteSale('${s.id}')">🗑️</button></div></div></div>`).join('')}</div>`}
function products(){return `<div class="sectionhead"><h2>সব পণ্য</h2><button class="btn primary" onclick="openProduct()">＋ Add Product</button></div>${!state.products.length?'<div class="card empty">কোনো পণ্য নেই।</div>':`<div class="list">${state.products.map(p=>`<div class="item"><div><h3>📦 ${esc(p.name)}</h3><p>Purchase Price: ${money(p.cost)} / pcs</p><p>Stock: <span class="${p.stock<=5?'low':''}">${bn(p.stock)} pcs</span></p><p>Stock Value: ${money(p.stock*p.cost)}</p></div><div class="actions"><button class="mini" onclick="viewProduct('${p.id}')">Details</button><button class="mini" onclick="editProduct('${p.id}')">✏️</button><button class="mini danger" onclick="deleteProduct('${p.id}')">🗑️</button></div></div>`).join('')}</div>`}`}
function expenses(){return `<div class="card hero"><div class="label">Total Expenses</div><div class="money">${money(state.expenses.reduce((x,e)=>x+e.amount,0))}</div></div><div class="section"><div class="sectionhead"><h2>➕ Add Expense</h2></div><div class="card form"><div class="field"><label>Expense Title</label><input id="expTitle" placeholder="Packaging"></div><div class="field"><label>Amount</label><input id="expAmount" type="number" min="0" placeholder="500"></div><div class="field"><label>Payment</label><select id="expPayment"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Bank</option></select></div><button class="btn primary" onclick="addExpense()">✓ SAVE EXPENSE</button></div></div><div class="section"><h2>Expense History</h2><div class="list">${state.expenses.slice().reverse().map(e=>`<div class="item"><div><h3>💸 ${esc(e.title)}</h3><p>${e.date} · ${esc(e.payment)}</p></div><div><strong>${money(e.amount)}</strong><button class="mini danger" onclick="deleteExpense('${e.id}')">🗑️</button></div></div>`).join('')||'<div class="card empty">কোনো খরচ নেই।</div>'}</div></div>`}
function reports(){const exp=state.expenses.reduce((x,e)=>x+e.amount,0),salesv=salesTotal(),prof=profitTotal();return `<div class="grid stats"><div class="card stat"><div class="label">Total Sales</div><div class="value">${money(salesv)}</div></div><div class="card stat"><div class="label">Total Profit</div><div class="value profit">${money(prof)}</div></div><div class="card stat"><div class="label">Expenses</div><div class="value">${money(exp)}</div></div><div class="card stat"><div class="label">Net Profit</div><div class="value ${prof-exp<0?'negative':'profit'}">${money(prof-exp)}</div></div></div><div class="section"><div class="card"><h2>Product-wise Report</h2><div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>Sold</th><th>Sales</th><th>Profit</th></tr></thead><tbody>${state.products.map(p=>{const a=state.sales.filter(s=>s.productId===p.id);return `<tr><td>${esc(p.name)}</td><td>${bn(a.reduce((x,s)=>x+s.qty,0))}</td><td>${money(salesTotal(a))}</td><td class="profit">${money(profitTotal(a))}</td></tr>`}).join('')||'<tr><td colspan="4">কোনো data নেই</td></tr>'}</tbody></table></div></div></div>`}
function settings(){return `<div class="card"><h2>Settings</h2><p>এই Version-এ data আপনার browser-এর Local Storage-এ সংরক্ষিত থাকে।</p><button class="btn danger" onclick="resetData()">সব Data মুছে ফেলুন</button></div>`}
function openModal(html){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="modalbox"><div class="modalhead"><h2>${html.title}</h2><button class="close" onclick="closeModal()">✕</button></div>${html.body}</div>`;document.body.appendChild(d)}function closeModal(){document.getElementById('modal')?.remove()}
function openProduct(p={}){openModal({title:p.id?'Edit Product':'Add Product',body:`<div class="form"><div class="field"><label>Product Name</label><input id="pName" value="${esc(p.name||'')}"></div><div class="field"><label>Purchase Price / pcs</label><input id="pCost" type="number" min="0" value="${p.cost??''}"></div><div class="field"><label>Initial Stock</label><input id="pStock" type="number" min="0" value="${p.stock??0}"></div><button class="btn primary" onclick="saveProduct('${p.id||''}')">✓ SAVE PRODUCT</button></div>`})}
function saveProduct(id){const name=document.getElementById('pName').value.trim(),cost=+document.getElementById('pCost').value,stock=+document.getElementById('pStock').value;if(!name||cost<0||stock<0)return toast('সঠিক তথ্য দিন');if(id){const p=state.products.find(x=>x.id===id);p.name=name;p.cost=cost;p.stock=stock}else state.products.push({id:crypto.randomUUID(),name,cost,stock});save();closeModal();render();toast('Product saved')}
function editProduct(id){openProduct(state.products.find(p=>p.id===id))}function deleteProduct(id){if(!confirm('এই Product মুছবেন?'))return;state.products=state.products.filter(p=>p.id!==id);save();render()}
function viewProduct(id){const p=state.products.find(x=>x.id===id),a=state.sales.filter(s=>s.productId===id);openModal({title:`📦 ${esc(p.name)}`,body:`<div class="grid stats"><div class="card stat"><div class="label">Purchase Price</div><div class="value">${money(p.cost)}</div></div><div class="card stat"><div class="label">Current Stock</div><div class="value">${bn(p.stock)} pcs</div></div><div class="card stat"><div class="label">Total Sold</div><div class="value">${bn(a.reduce((x,s)=>x+s.qty,0))}</div></div><div class="card stat"><div class="label">Total Profit</div><div class="value profit">${money(profitTotal(a))}</div></div></div><h3>Sales History</h3>${salesList(a.slice().reverse())}`})}
function openSale(){go('sales');setTimeout(()=>document.getElementById('salePrice')?.focus(),50)}function saleTotalPreview(){const q=+document.getElementById('saleQty')?.value||0,p=+document.getElementById('salePrice')?.value||0;if(document.getElementById('salePreview'))document.getElementById('salePreview').textContent=money(q*p)}
function addSale(){const pid=document.getElementById('saleProduct').value,q=+document.getElementById('saleQty').value,price=+document.getElementById('salePrice').value,pay=document.getElementById('salePayment').value,p=state.products.find(x=>x.id===pid);if(!p||q<1||price<0||q>p.stock)return toast('স্টক বা তথ্য ঠিক নেই');p.stock-=q;state.sales.push({id:crypto.randomUUID(),productId:pid,productName:p.name,cost:p.cost,qty:q,price,payment:pay,date:today()});save();render();toast('Sale saved')}
function deleteSale(id){const s=state.sales.find(x=>x.id===id);if(!s)return;if(!confirm('এই Sale মুছবেন? Stock ফিরিয়ে দেওয়া হবে।'))return;const p=state.products.find(x=>x.id===s.productId);if(p)p.stock+=s.qty;state.sales=state.sales.filter(x=>x.id!==id);save();render()}
function editSale(id){const s=state.sales.find(x=>x.id===id);openModal({title:'Edit Sale',body:`<div class="form"><div class="field"><label>Product</label><input value="${esc(s.productName)}" disabled></div><div class="field"><label>Quantity</label><input id="esQty" type="number" min="1" value="${s.qty}"></div><div class="field"><label>Selling Price / pcs</label><input id="esPrice" type="number" min="0" value="${s.price}"></div><div class="field"><label>Payment</label><select id="esPay"><option ${s.payment==='Cash'?'selected':''}>Cash</option><option ${s.payment==='bKash'?'selected':''}>bKash</option><option ${s.payment==='Nagad'?'selected':''}>Nagad</option><option ${s.payment==='Bank'?'selected':''}>Bank</option></select></div><button class="btn primary" onclick="updateSale('${id}')">✓ UPDATE SALE</button></div>`})}
function updateSale(id){const s=state.sales.find(x=>x.id===id),q=+document.getElementById('esQty').value,price=+document.getElementById('esPrice').value,pay=document.getElementById('esPay').value,p=state.products.find(x=>x.id===s.productId),diff=q-s.qty;if(diff>p.stock)return toast('পর্যাপ্ত stock নেই');p.stock-=diff;s.qty=q;s.price=price;s.payment=pay;save();closeModal();render();toast('Sale updated')}
function addExpense(){const title=document.getElementById('expTitle').value.trim(),amount=+document.getElementById('expAmount').value,payment=document.getElementById('expPayment').value;if(!title||amount<=0)return toast('সঠিক তথ্য দিন');state.expenses.push({id:crypto.randomUUID(),title,amount,payment,date:today()});save();render();toast('Expense saved')}
function deleteExpense(id){if(!confirm('এই Expense মুছবেন?'))return;state.expenses=state.expenses.filter(e=>e.id!==id);save();render()}
function go(p){page=p==='more'?'more':p;render()}function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}function resetData(){if(confirm('সব হিসাব মুছে ফেলবেন? এটি ফেরত আনা যাবে না।')){state=JSON.parse(JSON.stringify(defaultState));save();render()}}
render();
